export default [
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b39b7f5484d850014197528',
    hotel: 'MGM Grand',
    room: '5443',
    pickupDate: 'Wednesday, May 23',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 3pm',
    cartItems: [
      {
        name: 'Skirt',
        price: 699,
        id: 'skirt',
        quantity: 1,
      },
      {
        name: 'Dress',
        price: 1299,
        id: 'dress',
        quantity: 1,
      },
      {
        name: 'Tie',
        price: 599,
        id: 'tie',
        quantity: 1,
      },
      {
        name: 'Suit (3pc)',
        price: 2699,
        id: 'suit3',
        quantity: 1,
      },
    ],
    totalPrice: 5296,
    name: 'Rolf Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CjKaGGzOjaH4xB0xFH6UkzD',
    stripeCustomer: 'cus_D9drxJXjcjtFMP',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-07-02T05:28:21.821Z',
    __v: 0,
  },
  {
    promoCode: {
      name: '',
      amount: null,
    },
    starch: true,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b39a3cc9c9b0d00142c9766',
    hotel: 'Aria',
    room: '555',
    pickupDate: 'Wednesday 6-6',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday 7-2',
    returnHour: 'by 7am',
    cartItems: [
      {
        id: 'blouse',
        name: 'Blouse',
        price: 699,
        quantity: 3,
      },
      {
        id: 'suit2',
        name: 'Suit(2pc)',
        price: 2099,
        quantity: 3,
      },
    ],
    totalPrice: 8989,
    name: 'John Lorenz',
    email: 'rjohnlorenzgmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CjJF1GzOjaH4xB0qITBkzEk',
    stripeCustomer: 'cus_D9cTusmmvoEfPD',
    mailjet: 'error',
    twilio: 'success',
    created: '2018-07-02T04:02:20.724Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b3632b3aea90200145ef263',
    hotel: 'MGM Grand',
    room: '5435',
    pickupDate: 'Wednesday, May 23',
    pickupHour: 'after 12pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 7am',
    cartItems: [
      {
        name: 'Jeans',
        price: 999,
        id: 'jeans',
        quantity: 1,
      },
      {
        name: 'Skirt',
        price: 699,
        id: 'skirt',
        quantity: 1,
      },
      {
        name: 'Blazer/Jacket',
        price: 1299,
        id: 'blazer',
        quantity: 1,
      },
      {
        name: 'Suit (3pc)',
        price: 2699,
        id: 'suit3',
        quantity: 1,
      },
    ],
    totalPrice: 5696,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiMYwGzOjaH4xB0AYqPwvXr',
    stripeCustomer: 'cus_D8dqAB7MRoamT9',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-06-29T13:22:59.495Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b3598c0e67ff00014a966cd',
    hotel: 'MGM Grand',
    room: '34543',
    pickupDate: 'Wednesday, May 23',
    pickupHour: 'after 2pm',
    returnDate: 'Friday, May 25',
    returnHour: 'by 3pm',
    cartItems: [
      {
        name: 'Dress',
        price: 1299,
        id: 'dress',
        quantity: 1,
      },
      {
        name: 'Skirt',
        price: 699,
        id: 'skirt',
        quantity: 1,
      },
      {
        name: 'Suit (3pc)',
        price: 2699,
        id: 'suit3',
        quantity: 1,
      },
    ],
    totalPrice: 4697,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiCJHGzOjaH4xB0fiEN79ZK',
    stripeCustomer: 'cus_D8TFsX1yrfhO7U',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-06-29T02:26:08.626Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b359381e67ff00014a966cc',
    hotel: 'MGM Grand',
    room: '345645',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 12pm',
    returnDate: 'Wednesday, May 23',
    returnHour: 'by 7am',
    cartItems: [
      {
        name: 'Pants',
        price: 899,
        id: 'pants',
        quantity: 1,
      },
      {
        name: 'Blouse',
        price: 699,
        id: 'blouse',
        quantity: 1,
      },
      {
        name: 'Suit (2pc)',
        price: 2099,
        id: 'suit2',
        quantity: 1,
      },
      {
        name: 'Blazer/Jacket',
        price: 1299,
        id: 'blazer',
        quantity: 1,
      },
    ],
    totalPrice: 4996,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiBxbGzOjaH4xB0jjTCZIXA',
    stripeCustomer: 'cus_D8St0Ed8aiJNwt',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-06-29T02:03:45.255Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b3590dee67ff00014a966cb',
    hotel: 'MGM Grand',
    room: '4355',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 3pm',
    cartItems: [
      {
        name: 'Shirt',
        price: 699,
        id: 'shirt',
        quantity: 1,
      },
      {
        name: 'Pants',
        price: 899,
        id: 'pants',
        quantity: 1,
      },
      {
        name: 'Suit (3pc)',
        price: 2699,
        id: 'suit3',
        quantity: 1,
      },
    ],
    totalPrice: 4297,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiBmjGzOjaH4xB02kdwFP9E',
    stripeCustomer: 'cus_D8SiLuhhI6krpt',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-06-29T01:52:30.337Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b358fbce67ff00014a966ca',
    hotel: 'MGM Grand',
    room: '25',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 4pm',
    returnDate: 'Wednesday, May 23',
    returnHour: 'by 3pm',
    cartItems: [
      {
        name: 'Tie',
        price: 599,
        id: 'tie',
        quantity: 1,
      },
      {
        name: 'Dress',
        price: 1299,
        id: 'dress',
        quantity: 1,
      },
      {
        name: 'Skirt',
        price: 699,
        id: 'skirt',
        quantity: 1,
      },
    ],
    totalPrice: 3000,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiBi3GzOjaH4xB06VqanVEK',
    stripeCustomer: 'cus_D8SdhkrlkDYkO2',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-06-29T01:47:40.756Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b358dc4e67ff00014a966c9',
    hotel: 'MGM Grand',
    room: '345',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 12pm',
    returnDate: 'Wednesday, May 23',
    returnHour: 'by 3pm',
    cartItems: [
      {
        name: 'Suit (2pc)',
        price: 2099,
        id: 'suit2',
        quantity: 1,
      },
      {
        name: 'Suit (3pc)',
        price: 2699,
        id: 'suit3',
        quantity: 1,
      },
      {
        name: 'Blazer/Jacket',
        price: 1299,
        id: 'blazer',
        quantity: 1,
      },
    ],
    totalPrice: 6097,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiBZvGzOjaH4xB0YGUNNNmo',
    stripeCustomer: 'cus_D8SUqJqYPDBR16',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-06-29T01:39:16.623Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b358937e67ff00014a966c8',
    hotel: 'Aria',
    room: '3563',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 3pm',
    cartItems: [
      {
        name: 'Blazer/Jacket',
        price: 1299,
        id: 'blazer',
        quantity: 1,
      },
      {
        name: 'Suit (3pc)',
        price: 2699,
        id: 'suit3',
        quantity: 1,
      },
      {
        name: 'Suit (2pc)',
        price: 2099,
        id: 'suit2',
        quantity: 1,
      },
    ],
    totalPrice: 6097,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14801111111',
    stripeCharge: 'ch_1CiBH7GzOjaH4xB01UN87WeE',
    stripeCustomer: 'cus_D8SBhb04Blg48o',
    mailjet: 'success',
    twilio: 'error',
    created: '2018-06-29T01:19:51.031Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b358905e67ff00014a966c7',
    hotel: 'Aria',
    room: '087',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 3pm',
    cartItems: [
      {
        name: 'Blouse',
        price: 699,
        id: 'blouse',
        quantity: 1,
      },
      {
        name: 'Suit (2pc)',
        price: 2099,
        id: 'suit2',
        quantity: 1,
      },
    ],
    totalPrice: 3000,
    name: 'Erik Lorenz',
    email: 'ERIKSLORENZ@gmail.com',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiBGJGzOjaH4xB0SiiIlatF',
    stripeCustomer: 'cus_D8SAnKCmOInpyX',
    mailjet: 'success',
    twilio: 'success',
    created: '2018-06-29T01:19:01.350Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b35888be67ff00014a966c6',
    hotel: 'Aria',
    room: '23456',
    pickupDate: 'Wednesday, May 23',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 5pm',
    cartItems: [
      {
        name: 'Dress',
        price: 1299,
        id: 'dress',
        quantity: 1,
      },
      {
        name: 'Skirt',
        price: 699,
        id: 'skirt',
        quantity: 1,
      },
      {
        name: 'Blazer/Jacket',
        price: 1299,
        id: 'blazer',
        quantity: 1,
      },
    ],
    totalPrice: 3297,
    name: 'Erik Lorenz',
    email: '345',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiBEMGzOjaH4xB0dbmqPa9b',
    stripeCustomer: 'cus_D8S8VrYNfgqqO1',
    mailjet: 'error',
    twilio: 'success',
    created: '2018-06-29T01:16:59.785Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b358805e67ff00014a966c5',
    hotel: 'MGM Grand',
    room: '3466',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 2pm',
    returnDate: 'Wednesday, May 23',
    returnHour: 'by 7am',
    cartItems: [
      {
        name: 'Skirt',
        price: 699,
        id: 'skirt',
        quantity: 2,
      },
      {
        name: 'Dress',
        price: 1299,
        id: 'dress',
        quantity: 1,
      },
      {
        name: 'Vest',
        price: 699,
        id: 'vest',
        quantity: 1,
      },
    ],
    totalPrice: 3396,
    name: 'Erik Lorenz',
    email: '34647',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiBCCGzOjaH4xB03Af4FQ6o',
    stripeCustomer: 'cus_D8S69k1eXq3cRK',
    mailjet: 'error',
    twilio: 'success',
    created: '2018-06-29T01:14:45.665Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b3586a5e67ff00014a966c4',
    hotel: 'MGM Grand',
    room: '34656',
    pickupDate: 'Friday, May 25',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 5pm',
    cartItems: [
      {
        name: 'Shirt',
        price: 699,
        id: 'shirt',
        quantity: 1,
      },
      {
        name: 'Pants',
        price: 899,
        id: 'pants',
        quantity: 2,
      },
      {
        name: 'Blouse',
        price: 699,
        id: 'blouse',
        quantity: 1,
      },
    ],
    totalPrice: 3196,
    name: 'Erik Lorenz',
    email: '432536',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiB6WGzOjaH4xB0PBDVEwnr',
    stripeCustomer: 'cus_D8S0imGhXvx0n2',
    mailjet: 'error',
    twilio: 'success',
    created: '2018-06-29T01:08:53.815Z',
    __v: 0,
  },
  {
    starch: false,
    specialInstructions: null,
    status: 'Processed',
    pickedUp: null,
    checkedIn: null,
    outForDelivery: null,
    delivered: null,
    additionalTime: null,
    _id: '5b35856ce67ff00014a966c3',
    hotel: 'MGM Grand',
    room: '2454',
    pickupDate: 'Thursday, May 24',
    pickupHour: 'after 2pm',
    returnDate: 'Thursday, May 24',
    returnHour: 'by 7am',
    cartItems: [
      {
        name: 'Shirt',
        price: 699,
        id: 'shirt',
        quantity: 1,
      },
      {
        name: 'Pants',
        price: 899,
        id: 'pants',
        quantity: 1,
      },
      {
        name: 'Blouse',
        price: 699,
        id: 'blouse',
        quantity: 1,
      },
      {
        name: 'Blazer/Jacket',
        price: 1299,
        id: 'blazer',
        quantity: 1,
      },
    ],
    totalPrice: 3596,
    name: 'Lorenz',
    email: 'dscvf',
    phone: '+14802418725',
    stripeCharge: 'ch_1CiB1SGzOjaH4xB0gjAqm8VH',
    stripeCustomer: 'cus_D8RvXxLi68K4da',
    mailjet: 'error',
    twilio: 'success',
    created: '2018-06-29T01:03:40.125Z',
    __v: 0,
  },
];
